name: Run Scrapy Spider

on:
  push:
    branches:
      - main

jobs:
  scrapy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scrapy scrapy-playwright
          playwright install

      - name: Run Scrapy spider
        run: |
          scrapy crawl personagem -O status_personagens.json

      - name: Upload results to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: status_personagens.json
          path: status_personagens.json
